// Regenerates src/abi/Countersign.ts from the Foundry build output.
// Run after `forge build` in ../contracts:  npm run abi
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const artifact = resolve(here, '../../contracts/out/Countersign.sol/Countersign.json')
const out = resolve(here, '../src/abi/Countersign.ts')

const { abi } = JSON.parse(readFileSync(artifact, 'utf8'))
if (!Array.isArray(abi) || abi.length === 0) throw new Error(`No ABI in ${artifact}`)
writeFileSync(out, `// Generated by scripts/abi.mjs from contracts/out/Countersign.sol/Countersign.json. Do not edit.\nexport const countersignAbi = ${JSON.stringify(abi, null, 2)} as const\n`)
console.log(`Wrote ${abi.length} ABI entries to src/abi/Countersign.ts`)
